"""add watch_status field to series table

Revision ID: 5ad5b63c1a8e
Revises: 135986936a3d
Create Date: 2025-10-06 13:18:30.841988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad5b63c1a8e'
down_revision: Union[str, Sequence[str], None] = '135986936a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('watch_status', sa.String(length=20), nullable=True),
    sa.Column('seasons_count', sa.Integer(), nullable=True),
    sa.Column('episodes_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('updated_at', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_created_at'), 'series', ['created_at'], unique=False)
    op.create_index(op.f('ix_series_updated_at'), 'series', ['updated_at'], unique=False)
    op.create_index(op.f('ix_series_watched'), 'series', ['watched'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_watched'), table_name='series')
    op.drop_index(op.f('ix_series_updated_at'), table_name='series')
    op.drop_index(op.f('ix_series_created_at'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
