"""update_series_model

Revision ID: 90a46188769f
Revises: 5ad5b63c1a8e
Create Date: 2025-10-06 13:34:05.886385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a46188769f'
down_revision: Union[str, Sequence[str], None] = '5ad5b63c1a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('season_number', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('episode_current', sa.Integer(), nullable=True))
    op.drop_column('series', 'seasons_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('seasons_count', sa.INTEGER(), nullable=True))
    op.drop_column('series', 'episode_current')
    op.drop_column('series', 'season_number')
    # ### end Alembic commands ###
